FROM ubuntu:22.04
RUN apt update && \
  apt install -y \
  git make curl build-essential lsb-release && \
  curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
  echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |tee  /etc/apt/sources.list.d/pgdg.list && \
  apt update && \
  apt install postgresql-client-13

ENTRYPOINT ["tail", "-f", "/dev/null"]
